const express = require("express");
const router = express.Router();
const protect = require("../middleware/authMiddleware");
const { registerUser, loginUser, getMe, googleAuth, googleCallback } = require("../controllers/authController");
router.post("/register", registerUser);
router.post("/login", loginUser);
router.get("/me", protect, getMe);
router.get("/google", googleAuth);
router.get("/google/callback", googleCallback);
module.exports = router;
